### PR TITLE
Make it compile with ghc8+

### PR DESCRIPTION
**Pull request by maximevince**

### CODE REVIEW

**Comment by maximevince** [comment]
Oh wow, that was a mistake! Went a bit too fast when committing!

**Comment by maximevince** [comment]
Removed the binary which was committed by mistake, and added the tiny change that makes it compile with ghc 8+ on my Arch Linux machine.

**Comment by mrVanDalo** [comment]
Sweet! but you can see [on Travis](https://travis-ci.org/mrVanDalo/csv-to-qif/builds/251434653?utm_source=github_status&utm_medium=notification) this will break the build for the old ghc versions. 

Also there is a ghc8 travis job is missing.
@maximevince Do you know how to remove the old ghc (< 7.10) and add the  a ghc 8 ? 

I would do it myself if you have problems with that. but I need some time for that.

**Comment by maximevince** [comment]
Hey!
Oh yeah, it breaks older ghc versions now :/
I don't know how to change the travis config, I am not even a Haskell dev :)
I guess it's to be done in the ".travis.yml" file, but since I cannot verify it locally, before committing, I'll leave that to you, whenever you have time.

Cheers,
Maxime

**Comment by mrVanDalo** [comment]
I'll pin it in my todo list.

**Comment by mrVanDalo** [comment]
@maximevince I fixed it today. I will do some other fixes and make a release.

**Pull request closed without merging**
